---
info:
  title: Reflectivedllinjection
  description: Reflective DLL injection is a library injection technique in which
    the concept of reflective programming is employed to perform the loading of a
    library from memory into a host process.
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/ReflectiveDLLInjection
  x-cortex-tag: reflectivedllinjection
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: metasploit
openapi: 3.0.1
servers:
- url: "/"
