---
info:
  title: Mimikatz
  description: A little tool to play with Windows security
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/mimikatz
  x-cortex-tag: mimikatz
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: metasploit
openapi: 3.0.1
servers:
- url: "/"
